name: Docker Image CI

on:
  push:
    branches: [ "TECH_VJ" ]
  pull_request:
    branches: [ "TECH_VJ" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urluploader:$(date +%s)
